#!/bin/sh

cd "$(dirname "$0")"

time ./node_modules/.bin/uglifyjs client/*.js --source-map filename=client/dist/source.js.map -o client/dist/source.js
# cat client/*.js > client/dist/source.js

cat client/app.appcache.template > client/dist/app.appcache
echo "# `date`" >> client/dist/app.appcache
